version: '3'

services:
  keycloak:
    image: gleroy/keycloak-bcrypt
    environment:
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_HOSTNAME=${KC_HOSTNAME}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
    ports:
      - 80:8443
      - 80:8080
      - 9000:9000
    volumes:
      - ./conf/server.keystore:/opt/keycloak/conf/server.keystore
      - ./themes:/opt/keycloak/themes
    security_opt:
      - 'label:disable'
    command: ["start", "--db=postgres"]
